# Generated by Django 3.2.6 on 2021-08-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aisle',
            field=models.CharField(default='nope', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='items',
            field=models.ManyToManyField(blank=True, to='main_app.Item'),
        ),
    ]
