# Generated by Django 3.2.6 on 2021-09-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_auto_20210831_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
